### PR TITLE
Added filter with raw properties

### PR DESCRIPTION
**Pull request by ikrivosheev**
Issue: https://github.com/Portable-Network-Archive/liblzma-rs/issues/126

### CODE REVIEW

**Review by ChanTsune — COMMENTED** [review]
Thank you for your PR!

I apologize for not informing you in advance, but our policy is to avoid using macros unless absolutely necessary. Although it might make the code a bit redundant, could you please expand the macros?

Everything else looks good, so I will merge the PR once this is addressed!

**Comment by ikrivosheev** [comment]
@ChanTsune it's ok. I removed marcos and added delta filter. Could you review?

**Comment by ikrivosheev** [comment]
@ChanTsune if everything is ok can you publish release?

**Comment by ChanTsune** [comment]
@ikrivosheev 

Thank you for your work!
It seems that `manual.rs` also needs to include `pub const LZMA_FILTER_DELTA: lzma_vli = 0x03;`.

I will release it as soon as possible once all the tests pass.

**Comment by ikrivosheev** [comment]
@ChanTsune ups, thank you. Fixed.

**Review by ChanTsune — APPROVED** [review]

**Comment by ChanTsune** [comment]
@ikrivosheev 
Thank you for your contribution!

I’d love to include your name in the THANKS file. Do you have a preferred name you'd like us to use?

**Comment by ikrivosheev** [comment]
> @ikrivosheev Thank you for your contribution!
> 
> I’d love to include your name in the THANKS file. Do you have a preferred name you'd like us to use?

Thank you. My full name is `Ivan Krivosheev`.

**Pull request merged**
